var searchData=
[
  ['qunitconversion_38',['QUnitConversion',['../md__r_e_a_d_m_e.html',1,'']]],
  ['qaliasdictionary_39',['QAliasDictionary',['../class_q_alias_dictionary.html',1,'QAliasDictionary'],['../class_q_alias_dictionary.html#a73188295f49275e952a2067147243e06',1,'QAliasDictionary::QAliasDictionary()']]],
  ['qaliasdictionary_2ecpp_40',['qaliasdictionary.cpp',['../qaliasdictionary_8cpp.html',1,'']]],
  ['qaliasdictionary_2eh_41',['qaliasdictionary.h',['../qaliasdictionary_8h.html',1,'']]],
  ['qaliasdictionarytests_42',['QAliasDictionaryTests',['../class_q_alias_dictionary_tests.html',1,'QAliasDictionaryTests'],['../class_q_alias_dictionary_tests.html#a1fa0ae347f2401b569ffe9aeeb30e9a4',1,'QAliasDictionaryTests::QAliasDictionaryTests()']]],
  ['qaliasdictionarytests_2ecpp_43',['qaliasdictionarytests.cpp',['../qaliasdictionarytests_8cpp.html',1,'']]],
  ['qaliasdictionarytests_2eh_44',['qaliasdictionarytests.h',['../qaliasdictionarytests_8h.html',1,'']]],
  ['qlinearfunction_45',['QLinearFunction',['../class_q_linear_function.html',1,'QLinearFunction'],['../class_q_linear_function.html#a500f067f46a6aac24a10bdee7592377a',1,'QLinearFunction::QLinearFunction()'],['../class_q_linear_function.html#aaace5f5eb36c4f3effe11368f72c9de5',1,'QLinearFunction::QLinearFunction(double k, double b)']]],
  ['qlinearfunction_2ecpp_46',['qlinearfunction.cpp',['../qlinearfunction_8cpp.html',1,'']]],
  ['qlinearfunction_2eh_47',['qlinearfunction.h',['../qlinearfunction_8h.html',1,'']]],
  ['qlinearfunctiontests_48',['QLinearFunctionTests',['../class_q_linear_function_tests.html',1,'QLinearFunctionTests'],['../class_q_linear_function_tests.html#ad30f148cae6ecb4d6fff0a8385afc221',1,'QLinearFunctionTests::QLinearFunctionTests()']]],
  ['qlinearfunctiontests_2ecpp_49',['qlinearfunctiontests.cpp',['../qlinearfunctiontests_8cpp.html',1,'']]],
  ['qlinearfunctiontests_2eh_50',['qlinearfunctiontests.h',['../qlinearfunctiontests_8h.html',1,'']]],
  ['qunitconversionfamily_51',['QUnitConversionFamily',['../class_q_unit_conversion_family.html',1,'QUnitConversionFamily'],['../class_q_unit_conversion_family.html#ab230a64cd6ef38a4dd4e3adc9fbac2ad',1,'QUnitConversionFamily::QUnitConversionFamily()'],['../class_q_unit_conversion_family.html#a878dbd0340bf8d5d514e205e1ce08dc9',1,'QUnitConversionFamily::QUnitConversionFamily(const QString &amp;familyName, const QString &amp;baseUnit)']]],
  ['qunitconversionfamily_2ecpp_52',['qunitconversionfamily.cpp',['../qunitconversionfamily_8cpp.html',1,'']]],
  ['qunitconversionfamily_2eh_53',['qunitconversionfamily.h',['../qunitconversionfamily_8h.html',1,'']]],
  ['qunitconversionrule_54',['QUnitConversionRule',['../class_q_unit_conversion_rule.html',1,'QUnitConversionRule'],['../class_q_unit_conversion_rule.html#a320a90a7edb6921477fd1b82ca174c1b',1,'QUnitConversionRule::QUnitConversionRule()'],['../class_q_unit_conversion_rule.html#a7d1600fc4370c7ed33087eab7ed0df8f',1,'QUnitConversionRule::QUnitConversionRule(const QString &amp;family, const QString &amp;baseUnit, const QString &amp;unit, const QLinearFunction &amp;convertFunction)'],['../class_q_unit_conversion_rule.html#ab4a8729e611b00db2cdddde548e71673',1,'QUnitConversionRule::QUnitConversionRule(const QString &amp;family, const QString &amp;baseUnit, const QString &amp;unit, double k, double b)']]],
  ['qunitconversionrule_2ecpp_55',['qunitconversionrule.cpp',['../qunitconversionrule_8cpp.html',1,'']]],
  ['qunitconversionrule_2eh_56',['qunitconversionrule.h',['../qunitconversionrule_8h.html',1,'']]],
  ['qunitconvertor_57',['QUnitConvertor',['../class_q_unit_convertor.html',1,'QUnitConvertor'],['../class_q_unit_convertor.html#a516c0ca3212f3d548b35862d9c7f5eea',1,'QUnitConvertor::QUnitConvertor()']]],
  ['qunitconvertor_2ecpp_58',['qunitconvertor.cpp',['../qunitconvertor_8cpp.html',1,'']]],
  ['qunitconvertor_2eh_59',['qunitconvertor.h',['../qunitconvertor_8h.html',1,'']]],
  ['qunitconvertortests_60',['QUnitConvertorTests',['../class_q_unit_convertor_tests.html',1,'QUnitConvertorTests'],['../class_q_unit_convertor.html#a1f407847a5b78799e02a4982d0340aa3',1,'QUnitConvertor::QUnitConvertorTests()'],['../class_q_unit_convertor_tests.html#a21a5d46e503af20955b8fa1ac3317191',1,'QUnitConvertorTests::QUnitConvertorTests()']]],
  ['qunitconvertortests_2ecpp_61',['qunitconvertortests.cpp',['../qunitconvertortests_8cpp.html',1,'']]],
  ['qunitconvertortests_2eh_62',['qunitconvertortests.h',['../qunitconvertortests_8h.html',1,'']]]
];
