var searchData=
[
  ['qaliasdictionary_0',['QAliasDictionary',['../class_q_alias_dictionary.html',1,'']]],
  ['qaliasdictionary_2eh_1',['qaliasdictionary.h',['../qaliasdictionary_8h.html',1,'']]],
  ['qaliasdictionary_3c_20qstring_20_3e_2',['QAliasDictionary&lt; QString &gt;',['../class_q_alias_dictionary.html',1,'']]],
  ['qaliasdictionarytests_3',['qaliasdictionarytests',['../class_q_alias_dictionary_tests.html',1,'QAliasDictionaryTests'],['../class_q_alias_dictionary_tests.html#a1fa0ae347f2401b569ffe9aeeb30e9a4',1,'QAliasDictionaryTests::QAliasDictionaryTests()']]],
  ['qaliasdictionarytests_2ecpp_4',['qaliasdictionarytests.cpp',['../qaliasdictionarytests_8cpp.html',1,'']]],
  ['qaliasdictionarytests_2eh_5',['qaliasdictionarytests.h',['../qaliasdictionarytests_8h.html',1,'']]],
  ['qlinearfunction_6',['qlinearfunction',['../class_q_linear_function.html#aaace5f5eb36c4f3effe11368f72c9de5',1,'QLinearFunction::QLinearFunction(double k, double b)'],['../class_q_linear_function.html#a500f067f46a6aac24a10bdee7592377a',1,'QLinearFunction::QLinearFunction()'],['../class_q_linear_function.html',1,'QLinearFunction']]],
  ['qlinearfunction_2ecpp_7',['qlinearfunction.cpp',['../qlinearfunction_8cpp.html',1,'']]],
  ['qlinearfunction_2eh_8',['qlinearfunction.h',['../qlinearfunction_8h.html',1,'']]],
  ['qlinearfunctiontests_9',['qlinearfunctiontests',['../class_q_linear_function_tests.html#ad30f148cae6ecb4d6fff0a8385afc221',1,'QLinearFunctionTests::QLinearFunctionTests()'],['../class_q_linear_function_tests.html',1,'QLinearFunctionTests']]],
  ['qlinearfunctiontests_2ecpp_10',['qlinearfunctiontests.cpp',['../qlinearfunctiontests_8cpp.html',1,'']]],
  ['qlinearfunctiontests_2eh_11',['qlinearfunctiontests.h',['../qlinearfunctiontests_8h.html',1,'']]],
  ['qunitconversion_12',['QUnitConversion',['../index.html',1,'']]],
  ['qunitconversionfamily_13',['qunitconversionfamily',['../class_q_unit_conversion_family.html',1,'QUnitConversionFamily'],['../class_q_unit_conversion_family.html#a7fbf3e754d7cf7d9e11bead3952e2ed9',1,'QUnitConversionFamily::QUnitConversionFamily()=default'],['../class_q_unit_conversion_family.html#a878dbd0340bf8d5d514e205e1ce08dc9',1,'QUnitConversionFamily::QUnitConversionFamily(const QString &amp;familyName, const QString &amp;baseUnit)']]],
  ['qunitconversionfamily_2ecpp_14',['qunitconversionfamily.cpp',['../qunitconversionfamily_8cpp.html',1,'']]],
  ['qunitconversionfamily_2eh_15',['qunitconversionfamily.h',['../qunitconversionfamily_8h.html',1,'']]],
  ['qunitconversionrule_16',['qunitconversionrule',['../class_q_unit_conversion_rule.html',1,'QUnitConversionRule'],['../class_q_unit_conversion_rule.html#ab4a8729e611b00db2cdddde548e71673',1,'QUnitConversionRule::QUnitConversionRule(const QString &amp;family, const QString &amp;baseUnit, const QString &amp;unit, double k, double b)'],['../class_q_unit_conversion_rule.html#a7d1600fc4370c7ed33087eab7ed0df8f',1,'QUnitConversionRule::QUnitConversionRule(const QString &amp;family, const QString &amp;baseUnit, const QString &amp;unit, const QLinearFunction &amp;convertFunction)'],['../class_q_unit_conversion_rule.html#a740ceebd3a3e74c1fe383a7b6e33811e',1,'QUnitConversionRule::QUnitConversionRule()=default']]],
  ['qunitconversionrule_2ecpp_17',['qunitconversionrule.cpp',['../qunitconversionrule_8cpp.html',1,'']]],
  ['qunitconversionrule_2eh_18',['qunitconversionrule.h',['../qunitconversionrule_8h.html',1,'']]],
  ['qunitconvertor_19',['qunitconvertor',['../class_q_unit_convertor.html',1,'QUnitConvertor'],['../class_q_unit_convertor.html#ae1b74bed8a9b7330c0c72fa7bcefe90d',1,'QUnitConvertor::QUnitConvertor()']]],
  ['qunitconvertor_2ecpp_20',['qunitconvertor.cpp',['../qunitconvertor_8cpp.html',1,'']]],
  ['qunitconvertor_2eh_21',['qunitconvertor.h',['../qunitconvertor_8h.html',1,'']]],
  ['qunitconvertortests_22',['qunitconvertortests',['../class_q_unit_convertor_tests.html',1,'QUnitConvertorTests'],['../class_q_unit_convertor.html#a1f407847a5b78799e02a4982d0340aa3',1,'QUnitConvertor::QUnitConvertorTests'],['../class_q_unit_convertor_tests.html#a21a5d46e503af20955b8fa1ac3317191',1,'QUnitConvertorTests::QUnitConvertorTests()']]],
  ['qunitconvertortests_2ecpp_23',['qunitconvertortests.cpp',['../qunitconvertortests_8cpp.html',1,'']]],
  ['qunitconvertortests_2eh_24',['qunitconvertortests.h',['../qunitconvertortests_8h.html',1,'']]]
];
